2018-12-10 19:21:39,187 ERROR: Exception on /edit_profile [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 101, in edit_profile
    form.petname.data = current_user.petname
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'petname'
2018-12-10 19:22:47,528 ERROR: Exception on /auth/register [POST] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/app/auth/routes.py", line 45, in register
    email=form.email.data)
  File "<string>", line 4, in __init__
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 424, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 421, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/sqlalchemy/ext/declarative/base.py", line 747, in _declarative_constructor
    (k, cls_.__name__))
TypeError: 'petname' is an invalid keyword argument for User
2018-12-10 19:25:46,159 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-10 19:25:55,833 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-10 19:26:02,385 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 11:12:36,327 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 11:14:45,061 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 11:15:09,565 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:10:32,366 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:11:44,278 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:22:55,309 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:24:01,377 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:24:20,500 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:24:40,764 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:25:27,052 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:26:31,893 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:28:27,094 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:29:20,114 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:30:17,960 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:31:10,100 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:33:06,580 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:37:21,098 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:37:57,319 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:39:01,962 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:39:24,554 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-12 12:39:59,516 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
